import controller.demo
import controller.register_controller
import controller.user_controller
import controller.login_controller
import controller.news_controller
import controller.test_controller
import controller.reset_pass_controller
